"""SQL specs against a real workspace.

For CHECK, generated and DEFAULT expressions a SQL spec keeps sqlglot's
rendering, not the text as written. Whether the catalog echoes that rendering
back unchanged decides whether a SQL spec re-plans empty — only a workspace can
say. https://docs.databricks.com/aws/en/delta/generated-columns
"""

from __future__ import annotations

from pathlib import Path

import pytest

from deltaplan.executor import Executor
from deltaplan.history import MemoryHistory
from deltaplan.introspect import Introspector, WarehouseRunner
from deltaplan.loader import load_spec
from deltaplan.planning import plan_tables

pytestmark = pytest.mark.integration

SPEC = """\
CREATE TABLE ${schema}.orders (
  order_id  BIGINT NOT NULL COMMENT 'Surrogate key',
  placed_at TIMESTAMP,
  placed_on DATE GENERATED ALWAYS AS (CAST(placed_at AS DATE)),
  line_id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10),
  status    STRING DEFAULT 'new',
  amount    DECIMAL(18, 2),
  address   STRUCT<street: STRING NOT NULL, zip: STRING>,
  CONSTRAINT orders_pk PRIMARY KEY (order_id),
  CONSTRAINT positive_amount CHECK (amount > 0)
)
COMMENT 'Order facts'
CLUSTER BY (order_id)
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

ALTER TABLE ${schema}.orders SET TAGS ('domain' = 'sales');
"""


def test_a_sql_spec_round_trips(
    runner: WarehouseRunner, introspector: Introspector, schema: str, tmp_path: Path
) -> None:
    path = tmp_path / "orders.sql"
    path.write_text(SPEC)
    spec = load_spec(path, {"schema": schema})

    plan = plan_tables([spec], introspector, target="it", tool_version="0")
    result = Executor(runner, introspector, MemoryHistory()).apply(plan)
    assert result.ok, result.error

    again = plan_tables([spec], introspector, target="it", tool_version="0")
    assert again.empty, [
        (c.kind, c.path, c.before, c.after) for d in again.diffs for c in d.changes
    ]
