CREATE TABLE main.sales.`odd orders` (
  order_id BIGINT NOT NULL COMMENT 'It\'s the key',
  placed_at TIMESTAMP,
  placed_on DATE GENERATED ALWAYS AS (CAST(placed_at AS DATE)),
  line_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10),
  status STRING DEFAULT 'new',
  `my amount` DECIMAL(18, 2),
  address STRUCT<street: STRING NOT NULL COMMENT 'o\'brien lane', `zip code`: STRING>,
  lines ARRAY<STRUCT<sku: STRING, qty: INT>>,
  attrs MAP<STRING, STRING>,
  customer_id BIGINT,
  PRIMARY KEY (order_id),
  CONSTRAINT fk_c FOREIGN KEY (customer_id) REFERENCES main.sales.customers (id),
  CONSTRAINT positive CHECK (`my amount` > 0)
)
COMMENT 'Order\'s facts'
CLUSTER BY AUTO
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true', 'note' = 'back\\slash');
ALTER TABLE main.sales.`odd orders` SET TAGS ('domain' = 'sales', 'owner' = 'o\'brien');
GRANT SELECT ON TABLE main.sales.`odd orders` TO `data analysts`;
GRANT MODIFY, SELECT ON TABLE main.sales.`odd orders` TO `etl`;
