"""Reading `SHOW CREATE TABLE`, where a column's identity, generation and
default live — `information_schema.columns` reports none of them on a live
workspace, and drops nested NOT NULL and comments too (verified 2026-09-18).

The fixture below is the statement a serverless SQL warehouse returned, as is.
https://docs.databricks.com/aws/en/sql/language-manual/sql-ref-syntax-aux-show-create-table
"""

import pytest

from deltaplan.ddl import DdlError, read_columns
from deltaplan.model.types import Identity, Primitive
from deltaplan.typeparser import parse_type

LIVE = """\
CREATE TABLE workspace.deltaplan_probe_gen2.t (
  id BIGINT NOT NULL COMMENT 'key',
  placed_at TIMESTAMP,
  placed_on DATE GENERATED ALWAYS AS ( CAST(placed_at AS DATE) ),
  line_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10),
  always_id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  status STRING COLLATE UTF8_BINARY DEFAULT 'new',
  address STRUCT<street: STRING COLLATE UTF8_BINARY NOT NULL COMMENT 'st', zip: STRING COLLATE UTF8_BINARY>,
  CONSTRAINT `t_pk` PRIMARY KEY (`id`))
USING delta
COMMENT 'tbl'
CLUSTER BY (id)
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.constraints.positive' = 'line_id > 0',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.parquet.format.version.afe.internal' = '2.12.0')"""  # noqa: E501 - verbatim


def test_identity_generation_and_defaults() -> None:
    columns = read_columns(LIVE)
    assert columns["line_id"].identity == Identity(always=False, start=100, increment=10)
    assert columns["always_id"].identity == Identity(always=True, start=1, increment=1)
    assert columns["placed_on"].generated == "CAST(placed_at AS DATE)"
    assert columns["status"].default == "'new'"
    assert columns["placed_at"].identity is None
    assert columns["placed_at"].generated is None


def test_nested_not_null_and_comments_survive() -> None:
    address = read_columns(LIVE)["address"]
    assert address.type == parse_type(
        "struct<street:string not null comment 'st',zip:string>"
    )
    assert address.collation is None, "UTF8_BINARY is the default: nothing to say"


def test_a_non_default_collation_is_reported() -> None:
    columns = read_columns(
        "CREATE TABLE c.s.t (\n  name STRING COLLATE UTF8_LCASE,\n"
        "  tags STRUCT<v: STRING COLLATE UTF8_LCASE>\n) USING delta"
    )
    assert columns["name"].type == Primitive("string")
    assert columns["name"].collation == "UTF8_LCASE"
    assert columns["tags"].type is None
    assert columns["tags"].collation is not None


def test_a_literal_mentioning_the_collation_is_left_alone() -> None:
    columns = read_columns(
        "CREATE TABLE c.s.t (\n  s STRING COLLATE UTF8_BINARY "
        "DEFAULT 'COLLATE UTF8_BINARY'\n) USING delta"
    )
    assert columns["s"].default == "'COLLATE UTF8_BINARY'"


def test_something_sqlglot_cannot_read_is_an_error() -> None:
    with pytest.raises(DdlError):
        read_columns("CREATE TABLE c.s.t AS SELECT 1")
    with pytest.raises(DdlError):
        read_columns("CREATE TABLE (")


PROTECTED = """\
CREATE TABLE workspace.deltaplan_probe_mask2.t (
  id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  email STRING COLLATE UTF8_BINARY MASK `workspace`.`deltaplan_probe_mask2`.`m` USING COLUMNS(region),
  region STRING COLLATE UTF8_BINARY,
  ts TIMESTAMP_NTZ,
  v VARCHAR(10) COLLATE UTF8_BINARY,
  arr ARRAY<STRING COLLATE UTF8_BINARY>,
  m MAP<STRING COLLATE UTF8_BINARY, INT>)
USING delta
WITH ROW FILTER `workspace`.`deltaplan_probe_mask2`.`f` ON (region)
TBLPROPERTIES (
  'delta.feature.timestampNtz' = 'supported',
  'delta.parquet.format.version.afe.internal' = '2.12.0')"""  # noqa: E501 - verbatim


def test_a_masked_and_filtered_table_still_reads() -> None:
    """Live output for a table with a column mask and a row filter, which
    sqlglot can't parse — they're cut, and read from information_schema."""
    columns = read_columns(PROTECTED)
    assert columns["id"].identity == Identity(always=True, start=1, increment=1)
    assert columns["email"].type == Primitive("string")
    assert columns["v"].type == parse_type("varchar(10)")
    assert columns["arr"].type == parse_type("array<string>")
    assert columns["m"].type == parse_type("map<string,int>")
    assert all(column.collation is None for column in columns.values())


RESERVED = """\
CREATE TABLE workspace.deltaplan_dogfood.orders (
  order_id BIGINT NOT NULL,
  placed_on DATE GENERATED ALWAYS AS ( CAST(placed_at AS DATE) ),
  order_status STRING COLLATE UTF8_BINARY DEFAULT 'new',
  shipping STRUCT<street: STRING COLLATE UTF8_BINARY NOT NULL, zip: STRING COLLATE UTF8_BINARY>,
  select STRING COLLATE UTF8_BINARY COMMENT 'a reserved word as a name',
  CONSTRAINT `orders_pk` PRIMARY KEY (`order_id`))
USING delta
COMMENT 'Order facts'
CLUSTER BY (placed_on)"""  # noqa: E501 - verbatim


def test_a_reserved_word_as_a_name_still_reads() -> None:
    """Live output (dogfooding, 2026-09-19): Databricks prints a column called
    `select` without backticks, which sqlglot — like any parser — refuses."""
    columns = read_columns(RESERVED)
    assert set(columns) == {
        "order_id",
        "placed_on",
        "order_status",
        "shipping",
        "select",
    }
    assert columns["placed_on"].generated == "CAST(placed_at AS DATE)"
    assert columns["order_status"].default == "'new'"


def test_reserved_words_as_struct_field_names() -> None:
    columns = read_columns(
        "CREATE TABLE c.s.t (\n  a STRUCT<select: INT, from: STRING>,\n"
        "  `x y` INT) USING delta"
    )
    assert columns["a"].type == parse_type("struct<`select`:int,`from`:string>")
    assert "x y" in columns
